"""Generate remaining paper figures: connection types, output package tree, ablation chart."""
from __future__ import annotations
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
import json, glob, os

OUT = Path("docs/paper/figures")
OUT.mkdir(parents=True, exist_ok=True)

# ===================================================================
# Figure 3: Connection types summary (table-as-figure)
# ===================================================================
fig, ax = plt.subplots(figsize=(10, 4))
ax.axis("off")
ax.set_title("Connection Feature Types Generated by Language-3D", fontsize=12, fontweight="bold")

conn_data = [
    ("Bolted", "ISO 273 clearance\n+ DIN 912 counterbore", "4-8 holes\n+ fasteners"),
    ("Press-fit", "H7/p6 interference\nbore + shoulder", "bore +\nshoulder"),
    ("Snap-fit", "Cantilever hooks\n+ undercuts", "hooks +\nslots"),
    ("Adhesive", "Bonding grooves\n+ 0.2mm gap", "13\ngrooves"),
    ("Welded (butt)", "V-groove bevel\n45° preparation", "bevel\ncut"),
    ("Magnetic", "Magnet pocket\nØ8.1 × 3.5mm", "pocket\nrecess"),
    ("Dowel pin", "H7 slip-fit\nholes + pins", "2 holes\n+ 2 pins"),
    ("Set screw", "Radial threaded\nhole + screw", "tap hole\n+ screw"),
]

colors = ["#4285F4", "#34A853", "#EA4335", "#FBBC04",
          "#4285F4", "#34A853", "#EA4335", "#FBBC04"]

for i, (name, spec, ops) in enumerate(conn_data):
    col = i % 4
    row = i // 4
    x = 0.5 + col * 2.4
    y = 2.0 - row * 1.5
    box = mpatches.FancyBboxPatch((x, y), 2.0, 1.2, boxstyle="round,pad=0.1",
                                   facecolor=colors[i], alpha=0.15, edgecolor=colors[i], lw=1.5)
    ax.add_patch(box)
    ax.text(x + 1.0, y + 1.0, name, ha="center", va="center", fontsize=9, fontweight="bold", color=colors[i])
    ax.text(x + 1.0, y + 0.55, spec, ha="center", va="center", fontsize=6, color="#333")
    ax.text(x + 1.0, y + 0.15, ops, ha="center", va="center", fontsize=6, color="#666", style="italic")

ax.set_xlim(0, 10)
ax.set_ylim(0, 4)
plt.tight_layout()
fig.savefig(OUT / "fig3_connections.pdf", dpi=300, bbox_inches="tight")
fig.savefig(OUT / "fig3_connections.png", dpi=200, bbox_inches="tight")
plt.close()
print("Saved fig3_connections")

# ===================================================================
# Figure 4: Output package file tree
# ===================================================================
fig, ax = plt.subplots(figsize=(10, 6))
ax.axis("off")
ax.set_title("Engineering Package Output Structure", fontsize=12, fontweight="bold")

# Count files from latest run
run = sorted(glob.glob("data/runs/4wheel_dual_arm/*/engineering_package"))[-1]
file_counts = {}
for root, dirs, files in os.walk(run):
    rel = os.path.relpath(root, run)
    if rel == ".": rel = ""
    for f in files:
        ext = os.path.splitext(f)[1] or "other"
        file_counts[ext] = file_counts.get(ext, 0) + 1

tree_lines = [
    ("engineering_package/", 0, True),
    ("├── stl_parts/ (38 STL meshes)", 1, True),
    ("├── step_parts/ (38 STEP B-rep models)", 1, True),
    ("├── freecad_scripts/ (38 parametric .py scripts)", 1, True),
    ("├── ros2_package/", 1, True),
    ("│   ├── urdf/ (URDF + flat URDF)", 2, True),
    ("│   ├── meshes/ (38 STL for simulation)", 2, True),
    ("│   ├── launch/ (display + gazebo launch)", 2, True),
    ("│   └── config/ (ros2_control + joint_names)", 2, True),
    ("├── firmware/ (6 files: servo, DC motor, IK, odometry)", 1, True),
    ("├── assembly.stl (16MB, with fastener geometry)", 1, True),
    ("├── urdf.xml (49KB, MuJoCo-ready)", 1, True),
    ("├── bom.md (bill of materials with COTS P/N)", 1, True),
    ("├── assembly_guide.md (25KB step-by-step)", 1, True),
    ("├── design_report.json", 1, True),
    ("├── cable_routing_report.md", 1, True),
    ("├── power_report.md", 1, True),
    ("├── wiring_diagram.md", 1, True),
    ("└── README.md", 1, True),
]

for i, (line, indent, _) in enumerate(tree_lines):
    y = len(tree_lines) - i - 0.5
    ax.text(0.3, y, line, fontsize=7, fontfamily="monospace", va="center",
            color="#333")

# File count summary
total = sum(file_counts.values())
ax.text(6.5, len(tree_lines) - 1, f"Total: {total} files", fontsize=10, fontweight="bold", color="#4285F4")
for i, (ext, count) in enumerate(sorted(file_counts.items(), key=lambda x: -x[1])):
    y = len(tree_lines) - 2.5 - i * 0.5
    ax.text(6.5, y, f"  .{ext.strip('.')}: {count} files", fontsize=7, fontfamily="monospace", color="#666")

ax.set_xlim(0, 10)
ax.set_ylim(-1, len(tree_lines) + 1)
plt.tight_layout()
fig.savefig(OUT / "fig4_package.pdf", dpi=300, bbox_inches="tight")
fig.savefig(OUT / "fig4_package.png", dpi=200, bbox_inches="tight")
plt.close()
print("Saved fig4_package")

# ===================================================================
# Figure 5: Ablation bar chart
# ===================================================================
fig, axes = plt.subplots(1, 2, figsize=(10, 4))

# Left: Variance (4dof_arm 3 runs)
ax1 = axes[0]
runs = ["Run 1", "Run 2", "Run 3"]
scores = [95.1, 95.1, 95.1]
bars = ax1.bar(runs, scores, color="#4285F4", width=0.5)
ax1.set_ylim(90, 100)
ax1.set_ylabel("Score (%)")
ax1.set_title("(a) Reproducibility (4dof\\_arm, 3 runs)", fontsize=9)
ax1.axhline(y=95.1, color="#EA4335", linestyle="--", linewidth=0.8, label=f"Mean=95.1%, σ=0.0%")
ax1.legend(fontsize=7)
for bar, score in zip(bars, scores):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
             f"{score:.1f}%", ha="center", fontsize=8)

# Right: Ablation (baseline vs no_geo)
ax2 = axes[1]
configs = ["Full\nsystem", "No geo\narbitration"]
ab_scores = [95.3, 95.3]
colors_ab = ["#34A853", "#FBBC04"]
bars2 = ax2.bar(configs, ab_scores, color=colors_ab, width=0.5)
ax2.set_ylim(90, 100)
ax2.set_ylabel("Score (%)")
ax2.set_title("(b) Ablation (4wheel\\_dual\\_arm)", fontsize=9)
ax2.text(0.5, 0.15, "Identical score: arbitration\nprevents dead-loops, not\nscore changes on clean input",
         transform=ax2.transAxes, ha="center", fontsize=6, style="italic", color="#666",
         bbox=dict(boxstyle="round", facecolor="#F0F0F0", alpha=0.8))
for bar, score in zip(bars2, ab_scores):
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
             f"{score:.1f}%", ha="center", fontsize=8)

plt.tight_layout()
fig.savefig(OUT / "fig5_ablation.pdf", dpi=300, bbox_inches="tight")
fig.savefig(OUT / "fig5_ablation.png", dpi=200, bbox_inches="tight")
plt.close()
print("Saved fig5_ablation")

print("All figures done.")
